84 fazer menu funcionar
tecMTST/aventuras-sampa pull request #113
Opened 2024-08-06 04:16 UTC by Kelvysb

Adicionadas as funcionalidades pendentes dos menus.
Adicionado o salvamento e carregamento automático das opções globais
Adicionados os controles de volume de Musica e de SFX

2024-08-07 00:54 UTC, mihailov-vf requested changes

2024-08-07 00:54 UTC, mihailov-vf commented on projeto/elementos/scripts/func_globais.gd
> +func map(value, low1, high1, low2, high2):
Existe uma função nativa do godot pra fazer esse mapeamento de valores:
3.x - https://docs.godotengine.org/en/3.6/classes/class_@gdscript.html#class-gdscript-method-range-lerp
4.x - https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#class-globalscope-method-remap

Creio que vale a pena usá-la nesse caso

2024-08-07 00:54 UTC, mihailov-vf commented on projeto/recursos/feed_de_noticias/AudioStreamEfeitos.gd
> +	_check_volume()
Aqui é mais uma dúvida.

Vale a pena usar signals para indicar a mudança de volume no singleton ao invés de depender de checagens constantes no processamento?

Caso sim, esse comentário vale para os demais casos de volume como este.

2024-08-07 00:54 UTC, mihailov-vf commented on projeto/recursos/jogos/enchente/jogador/AudioStreamPlayer.gd
> +			stream_paused = true
Atribuição duplicada

2024-08-07 01:23 UTC, mihailov-vf commented on projeto/elementos/scripts/func_globais.gd
> +	SingletonOpcoesGlobais.ativarBotoes = Salvamento.carregar("globais", "ativarBotoes")
Necessário garantir que o valor retornado do carregamento seja do mesmo tipo que as variáveis do singleton.

Erro no carregamento inicial quando não há salvamento anterior:
![image](https://github.com/user-attachments/assets/58dddee1-e18c-4af9-ab13-fb6eca194d34)

2024-08-07 12:23 UTC, Kelvysb commented on projeto/recursos/feed_de_noticias/AudioStreamEfeitos.gd
> +	_check_volume()
Boa ideia vou ver um método de faze dessa maneira.

2024-08-07 12:39 UTC, Kelvysb commented on projeto/elementos/scripts/func_globais.gd
> +	SingletonOpcoesGlobais.ativarBotoes = Salvamento.carregar("globais", "ativarBotoes")
Ok Adicionando um checagem, e tratamento de tipos

2024-08-09 14:47 UTC, mihailov-vf commented
@Kelvysb, além do conflito que apareceu, temos também alguns problemas com os assets antigos do menu aplicados.
Se puder fazer uma limpa dos arquivos .import do projeto, vai ver que está quebrando a execução.

Além disso, um detalhe sobre os assets novos. Eles não tem texto, portanto precisa aplicar os textos por label nos botões e nos indicadores de volume, etc.

2024-08-09 19:24 UTC, Kelvysb commented
Correções feitas.

2024-08-10 23:48 UTC, mihailov-vf commented
Realizei algumas correções associadas a esta branch para os assets do menu no PR #122 
Fazer o merge da #122 primeiro ou alterar o destino pra main.

2024-08-11 22:05 UTC, rodigu requested changes
Esconder opcoes de dificuldade

2024-08-11 22:14 UTC, rodigu approved these changes

2024-08-11 22:18 UTC, mihailov-vf approved these changes

2024-08-11 22:18 UTC, merged