82 cutscene
tecMTST/aventuras-sampa pull request #114
Opened 2024-08-08 03:44 UTC by Kelvysb

Adicionado dialogic,
adicionados assets disponíveis no storyboard,
implementada a cutscene.

2024-08-09 00:38 UTC, rodigu requested changes
Espaço cinza em tamanhos de tela comuns (Samsung s20, s10, iphone 11)
Tem como resolver?

![image](https://github.com/user-attachments/assets/3dfd9d32-827a-413a-9157-b1d7fce9ce9d)

![image](https://github.com/user-attachments/assets/53e19287-5c5d-4d27-91c5-adf5d5a049d8)

![image](https://github.com/user-attachments/assets/9fac0bec-f828-4242-a4a5-497c9e40e74c)

2024-08-09 00:44 UTC, mihailov-vf reviewed
@Kelvysb  Gostei da solução com o plugin e o funcionamento dos eventos, parabéns mano!

Só fiquei em dúvida quanto a um pontos:
Vi que tem duas timelines do dialogic, a que está sendo usada é a `enchente-cutscene`. A outra tem alguma função secundário ou pode ser removida?

2024-08-09 12:11 UTC, Kelvysb commented
> @Kelvysb Gostei da solução com o plugin e o funcionamento dos eventos, parabéns mano!
> 
> Só fiquei em dúvida quanto a um pontos: Vi que tem duas timelines do dialogic, a que está sendo usada é a `enchente-cutscene`. A outra tem alguma função secundário ou pode ser removida?

Uma contem o texto integral, não sei ainda qual será o texto completo, ache que algumas falas do narrador ficaram duplicadas, por isso fiquei em duvida sobre quais falas devem entrar ja que no storyboard tem dois tipos de falas do narrador, ama sacho que posso deletar sim a que não esta sendo utilizada.

2024-08-09 19:24 UTC, Kelvysb commented
Correções feitas

2024-08-11 21:54 UTC, rodigu approved these changes

2024-08-11 22:01 UTC, mihailov-vf approved these changes

2024-08-11 22:02 UTC, merged