novo menu feed de noticias finalizado
tecMTST/aventuras-sampa pull request #129
Opened 2024-08-18 02:11 UTC by ClockWritesDev

Não dêem merge ainda, falta finalizar o like, preciso que o miha revise o codigo do plugin de salvamento pois ele não ta enviando o dicionario completo com o id a chave e o dado, preciso do dado e o plugin não tem essa função de puxar esse dado.

#128

2024-08-18 19:19 UTC, rodigu requested changes
diminuir o delay antes do card aparecer

2024-08-18 19:38 UTC, rodigu commented
#117

2024-08-19 02:24 UTC, ClockWritesDev commented
versão final ja com push, espero que esteja funcionando pq não consigo ver o commit, porém segundo o github as mudanças ja estão no feed

2024-08-22 23:13 UTC, rodigu approved these changes

2024-08-22 23:41 UTC, mihailov-vf approved these changes

2024-08-22 23:44 UTC, merged